ARG FLOOD_VERSION=latest
ARG RTORRENT_VERSION=latest

FROM jesec/rtorrent:$RTORRENT_VERSION as rtorrent

FROM jesec/flood:$FLOOD_VERSION as flood

# Install rTorrent
COPY --from=rtorrent / /

# Flood with managed rTorrent daemon
ENTRYPOINT ["/sbin/tini", "--", "flood"]
CMD ["--host=0.0.0.0", "--rtorrent"]
