ARG FLOOD_IMAGE=jesec/flood:latest
ARG RTORRENT_IMAGE=jesec/rtorrent:latest

FROM ${RTORRENT_IMAGE} AS rtorrent

FROM ${FLOOD_IMAGE} AS flood

# Install rTorrent
COPY --from=rtorrent / /

# Flood with managed rTorrent daemon
ENV FLOOD_OPTION_RTORRENT="true"
