# Use node alpine docker image
FROM node:alpine

# Get the latest release from npm
RUN npm i -g flood --unsafe-perm

# Install runtime dependencies
RUN apk --no-cache add \
    mediainfo su-exec

# Expose port 3000
EXPOSE 3000

# Copy docker entrypoint script
COPY docker-entrypoint.sh /

# Flood
ENTRYPOINT ["/docker-entrypoint.sh", "flood", "--host=0.0.0.0"]
