FROM jesec/rtorrent as rtorrent

FROM jesec/flood

# Install rTorrent
COPY --from=rtorrent /usr/local/bin/rtorrent /usr/local/bin/

# Default rTorrent configuration
# SCGI socket is exposed to $HOME/.local/share/rtorrent/rtorrent.sock
# With "download" user, /home/download/.local/share/rtorrent/rtorrent.sock
COPY --from=rtorrent /etc/rtorrent/rtorrent.rc /etc/rtorrent/

# Flood with managed rTorrent daemon
ENTRYPOINT ["flood", "--host=0.0.0.0", "--rtorrent"]
