FROM node:7.8.0

# Install runtime dependencies and remove state generated by apt-get before
# creating intermediate image.
RUN apt-get update && apt-get install -y mediainfo && rm -rf /var/lib/apt/lists/*

# Create app working directory.
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app

# Copy docker configuration file. This allows for specifying common configs with
# just environment variables.
COPY config.docker.js /usr/src/app/config.js

# Install Dependencies and remove cache to keep image small. This is done in one
# step to keep the cache out of intermediate image.
RUN npm install && npm cache clean --force

# Build static assets.
RUN npm run build

# Hints for consumers of the container.
EXPOSE 3000
VOLUME ["/data"]

# Start application.
CMD [ "npm", "start" ]
