nodeLinker: hoisted
trustLockfile: true
hoistPattern:
  - '!@lingui/*'
allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeStrict: false
patchedDependencies:
  bencode@4.0.1: patches/bencode@4.0.1.patch
