const ActionTypes = {
  CLIENT_ADD_TORRENT_ERROR: 'CLIENT_ADD_TORRENT_ERROR',
  CLIENT_ADD_TORRENT_SUCCESS: 'CLIENT_ADD_TORRENT_SUCCESS',
  CLIENT_FETCH_TORRENT_DETAILS_ERROR: 'CLIENT_FETCH_TORRENT_DETAILS_ERROR',
  CLIENT_FETCH_TORRENT_DETAILS_SUCCESS: 'CLIENT_FETCH_TORRENT_DETAILS_SUCCESS',
  CLIENT_FETCH_TORRENTS_ERROR: 'CLIENT_FETCH_TORRENTS_ERROR',
  CLIENT_FETCH_TORRENTS_SUCCESS: 'CLIENT_FETCH_TORRENTS_SUCCESS',
  CLIENT_FETCH_TRANSFER_DATA_ERROR: 'CLIENT_FETCH_TRANSFER_DATA_ERROR',
  CLIENT_FETCH_TRANSFER_DATA_SUCCESS: 'CLIENT_FETCH_TRANSFER_DATA_SUCCESS',
  CLIENT_SET_THROTTLE_ERROR: 'CLIENT_SET_THROTTLE_ERROR',
  CLIENT_SET_THROTTLE_SUCCESS: 'CLIENT_SET_THROTTLE_SUCCESS',
  CLIENT_START_TORRENT_ERROR: 'CLIENT_START_TORRENT_ERROR',
  CLIENT_START_TORRENT_SUCCESS: 'CLIENT_START_TORRENT_SUCCESS',
  CLIENT_STOP_TORRENT_ERROR: 'CLIENT_STOP_TORRENT_ERROR',
  CLIENT_STOP_TORRENT_SUCCESS: 'CLIENT_STOP_TORRENT_SUCCESS',
  UI_CLICK_TORRENT: 'UI_CLICK_TORRENT',
  UI_CLICK_TORRENT_DETAILS: 'UI_CLICK_TORRENT_DETAILS',
  UI_DISPLAY_MODAL: 'UI_DISPLAY_MODAL',
  UI_SET_TORRENT_SEARCH_FILTER: 'UI_SET_TORRENT_SEARCH_FILTER',
  UI_SET_TORRENT_SORT: 'UI_SET_TORRENT_SORT',
  UI_SET_TORRENT_STATUS_FILTER: 'UI_SET_TORRENT_STATUS_FILTER'
};

export default ActionTypes;
