export interface WatchedDirectory {
  type: 'watchedDirectory';
  // Unique ID of the feed, generated by server by the time the feed is added.
  _id: string;
  // User-facing label (name) of the feed.
  label: string;
  // URL of the feed.
  dir: string;
  // How many times rules have matched items of the feed.
  count?: number;
  destination: string;
  tags: string[]
}

export interface WatchItem {
  file: string, //Based64 file
  filename: string //FileName
}
